services:
  - type: web
    name: memathesisbackend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: gunicorn translate_to_chinese:app
